const constants = {
  ETH: 'ETH',
  MKR: 'MKR',
  DGD: 'DGD',
  VHT:'VHT',
  ACT:'ACT',
  CPCE:'CPCE',
  Token:'Token',
  mywallet: 'mywallet',
  walletList: 'walletList',
  mywalletinfo: 'mywalletinfo',
  ethCH:'ethCH',
  ethBL:'ethBL',
  vhtBL:'vhtBL',
  vhtCH: 'vhtCH',
  actBL: 'actBL',
  actCH: 'actCH',
  cpceBL: 'cpceBL',
  cpceCH: 'cpceCH',
  qtumBL:'qtumBL',
  qtumCH: 'qtumCH',
  cpcBL: 'cpcBL',
  cpcCH: 'cpcCH',
  myVHT:'myVHT',
  myACT:'myACT',
  myCPCE:'myCPCE',
  txinfo:'txinfo',
  Txinfo: 'Txinfo',
  vhtinfo:'vhtinfo',
  Vhtinfo: 'Vhtinfo',
  actinfo: 'actinfo',
  Actinfo: 'Actinfo',
  cpceinfo: 'cpceinfo',
  Cpceinfo: 'Cpceinfo',
  qtuminfo: 'qtuminfo',
  Qtuminfo: 'Qtuminfo',
  cpcinfo: 'cpcinfo',
  Cpcinfo: 'Cpcinfo',
  allBalance:'allBalance',
  tmpTrans:'tmpTrans',
  tmptokenTrans:'tmptokenTrans'
}

module.exports = constants